### ISSUE TITLE
Order of standardizing transformation and evaluation of function

### ISSUE THREAD

**Issue by dmbates** [beacon-biosignals/StandardizedPredictors.jl#22]
I was trying to fit a quadratic growth curve model where the time covariate should be centered for the coefficients to be meaningful.  That is I want `time` to be centered about the mean and `time^2` to be the square of the centered time.  If I use
```jl
@formula(resp ~ 1 + time + time^2), contrasts=Dict(:time => Center())
```
then the linear term is centered but the `time` in the quadratic term is on the original scale.

Is there a way to express a function like `abs2` or `time^2` of a standardized predictor?

**Comment by kleinschmidt** [comment]
I think there are two ways to address this.  First, you could define a `poly` syntax that creates a special term type, which then wraps ANY term (including a CenteredTerm) and calls modelcols on those before evaluating the higher power bits.  Second, you could re-write the plumbing of function terms to do something similar: instead of directly accessing the input columns based on names, use the existing term machinery to pull out (possibly transformed) values from the input table.  That's the approach that https://github.com/JuliaStats/StatsModels.jl/pull/183 takes

**Comment by dmbates** [comment]
I like the first suggestion but I might carry it a bit further.  In R the default contrasts for an ordered factor are polynomial contrasts and I was thinking of creating a `poly` function to generate those.  My plan was to create orthogonal polynomial contrasts for a numeric vector by creating a matrix of powers of the vector, and returning the columns of the Q matrix from a QR decomposition.  Something like
```jl
"""
    orthpoly(x, n)

Return a matrix of `n` orthogonal polynomial contrasts for the positions `x`
"""
function orthpoly(x::AbstractVector{<:Real}, n::Integer)
    return Matrix(qr!(float([v^i for v in x, i in 0:n])).Q)[:, 2:(n+1)]
end
```

I am not terribly familiar with `modelcols` in `StatsModels` but I can read the docs.  I was just wondering if you had an "off the top of my head" reaction to this and, more importantly, am I neglecting existing approaches.

**Comment by palday** [comment]
I think this would be a great thing to have. The example of extending the formula syntax in the StatsModels docs is a naive, [non-orthogonal polynomial](https://juliastats.org/StatsModels.jl/stable/internals/#An-example-of-custom-syntax:-poly). It also wouldn't have occurred to me to use the QR decomposition for this, but of course it's just the numerically smart way to do a naive polynomial basis and then apply Graham-Schmidt. :smile: 

@kleinschmidt can express his opinion, but I don't know if `orthopoly` would be more at home here or in [`RegressionFormulae.jl`](https://github.com/kleinschmidt/regressionformulae.jl).

**Comment by kleinschmidt** [comment]
@dmbates the tricky thing is that you need to make sure that whatever you do it's portable to different subsets of the data/out-of-sample prediction.  So if you want to orthogonalize, you need to store the coefficients in the term somewhere, which is why it seems like composing with centered terms might be a lower friction way to go here.

**Comment by kleinschmidt** [comment]
The other tricky thing with orthogonalization is that we really strive to keep all the invariant computation/storage to the schema extraction stage, and right now it's hard to hook into that with custom syntax (since custom syntax inside the `@formula` gets applied only at the `apply_schema` stage).  So you could perhaps do it with contrasts (`hints=` in teh schema functions) but I'm not sure that's as nice as being able to say `@formula(y ~ poly(x, 3))`

**Comment by dmbates** [comment]
I think that subsets/prediction issue could be handled by storing the `R` matrix from the `QR` decomposition.  It (or its inverse, I'm not sure) would function like a contrasts matrix.

But I agree that this approach may be too specialized.  As it turns out that I am not actually using orthogonal polynomial contrasts in the example that got me thinking about this, maybe I will move on and think about this later.

Thanks for answering my questions.
